# Vježbe 1 
## Prvi dio

#### Teme:
1. ponavljanje linearne algebre & matematičke analize
2. upoznavanje s JupyterLab radnom okolinom
    - kako koristiti JupyterLab
    - markdown
    - predaja zadaće
4. upoznavanje biblioteke Numpy
5. upoznavanje biblioteke Matplotlib
6. upoznavanje biblioteke scikit-learn

#### 1. ponavljanje linearne algebre & matematičke analize
[PDF](https://fizika-my.sharepoint.com/:b:/g/personal/djaganja_unios_hr/Ebdzm08U6tlFuHLR0lEBT60BWRmgumjyVtmcPKkQ5cW9iw?e=77LhRj)

#### 2. Upoznavanje s JupyterLab radnom okolinom

Za rješavanje zadataka na vježbama i za rješavanja/predaju zadaće koristit ćemo JupyterLab radnu okolinu. Jedan od načina kako možemo koristiti (kako će biti prezentirano na vježbama) je da lokalno instalirate _Anacondu_ (Pratite upute na: https://docs.anaconda.com/anaconda/). Zatim, ako preferirate grafičko korisničko sučelje, iz Anaconda Navigatora pokrente lokalno JupyterLab. 
<img src="img1.png" width="800px" />

Alternativno, možete koristiti Google Colab (https://colab.research.google.com/notebooks/intro.ipynb#recent=true). 
   - koristi se online
   - preporuka je da se ulogirate sa svojim Google računom
   - podatke koje ćete učitati možete staviti u direktorij koji se prikaže na lijevoj strani, **ali** ti podaci se brišu nakon kratkog vremena
        - bolji način -> podatke učitavate na vaš Google Drive, detaljne upute imate na internetu, npr: https://colab.research.google.com/notebooks/io.ipynb
        
##### Zašto koristimo JupyterLab ( ili Colab) ? 
- grafičko korisničko sučelje i jednostavno za koristiti
- sve mogućnosti Pythona
- sve dodatne biblioteke za Data Science, Machine Learning i sl. 
- pisanje teksta (Markdown) i stručnog teksta (Latex)
- umetanje datoteka/slika/grafova


##### Kako ćete predavati zadaću? 
- Zadaću ćete pisati u JupyterLab bilježnici (Colab bilježnici)
- Sve zadatke možete riješiti u jednoj bilježnici 
- Programerske zadatke rješavate na uobičajen način (pišete kod u ćelijama bilježnice ili napišete skripte (.py datoteke) koje onda pozivate u ćelijama bilježnice )
- Teorijske zadatke pišete u Markdownu (Latexu) ili (ukoliko su neki složeni raspisi) skenirane/uslikane datoteke umetnene u Jupyter bilježnicu 
- JupyterLab: Bilježnicu/zip file pošaljete / Ili ako koristite Google Colab dovoljno je da podijelite link na bilježnicu -> Teams->Zadaće->Assignments

##### Kako koristiti Markdown?
Cijeli ovaj prethodni tekst je napisan u Markdownu. Markdown je markup jezik, super jednostavan za korištenje (s kojim ste se dosad markup jezicima susreli?)<br>
Jupyter bilježnica se sastoji od ćelija. Kada Dodamo novu ćeliju možemo odabrati njen format, ponuđeni su: Markdowm, Code, Raw. <br>
Mi ćemo koristiti Markdown za pisanje teksta i code za pisanje Python koda. <br>

Nakon što ste dodali novu ćeliju i označili je kao Markdown, možete počet pisati tekst. <br>

Naslove dodajemo stavljajući znak # na početak reda željeni broj puta, tako imamo naslove u različitim veličinama
# H1
## H2
### H3
#### H4
##### H5
###### H6

Ako želimo razdovojiti tekst horizontalnom linijom preko cijele stranice napišemo tri uzastopne crtice --- ili ___ na početak reda (dodani jedan prazan red)

---

U tekstu možemo dijelove naglašavati **podebljavanjem** na __dva načina__ ili ukošenim *slovima* također na _dva načina_. 

---

Ako želimo tekst posložiti u numeriranu ili nenumeriranu listu to radimo na sljedeći način:
1. stavimo redni broj
2. iza njega jedan razmak
3. i samo nižemo stavke sa liste
4. jednu ispod druge

Dok za neneumeriranu listu je dovoljno
- staviti jednu crticu
- i iza nje jedan razmak
- također možemo korstiti
* znak asterisk
+ ili znak plus

Liste možemo ugnijezditi koristeći dovoljan razmak (tab)
1. Zadatak 
    1. podzadatak
    2. podzadatak
2. Zadatak
    1. podzadatak
- Treći zadatak
    - prvi podzadatak
    - drugi podzadatak
        - prvi podpodzadatak
        

##### Latex 
Unutar Markdowna možemo pisati Latex kod (tekst). Latex pišemo unutar simbola $

Primjeri: 
- $f(x) = \frac{1}{2}x^3$
- $a_0^n$
- $A\in \mathbb{R}^{n\times n}$
- $||x||_2 = \sqrt{\sum\limits_{i=1}^{n}|x_i|^2}$
        
---

Jupyter bilježnicu možete izvesti u pdf ili html oblik, zatim kao Python skriptu i sl. 
- Upute: gore lijevo u izborniku File/Export notebook as

#### Upoznavanje biblioteka

- učitavanje


In [2]:
# begin standard imports
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
#end standard imports 

### Arrays

#### Zadatak 1: Kreiranje Numpy arraya

##### Shape
Numpy arrays imaju atribut **shape** čiji je tip uređeni par. 
- array duljine n ima shape (n,)
- matrica sa m redaka i n stupaca ima shape (m,n) 
- arrayji mogu imati više od dvije dimenzije (axis)
    - npr: ako je a.shape = (3,2,4) onda je $a \in \mathbb{R}^{3\times 2 \times 4} $

In [ ]:
#1.1 arrays created from python array

a = np.array([1,2,3])
b = np.array([[1,2,3],[4,5,6]])
print(a)
print(b)

#1.2 array comprehensions work well
array = np.array([x/2 for x in range(1,5)])
print(array)


# Shape
print(a.shape)
# Reshape 1D to 2D 
# -1 as unspecified
a = a.reshape(-1,1)
print(a.shape)

# Reshape generally
b.reshape(3,2)

# Find out dimensions of array
print(a.shape)
print(b.shape)
print(array.shape)


#### Zadatak 2: Kreiranje višedimenzionalnih numpy arrayja

In [3]:
# Similar operations with multi-dimensional arrays (matrices)

# brute force
array = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(array)

# "double comprehension"
array = np.array([[x for x in range(i,j+1)] 
                    for (i,j) in [(1,3),(4,6),(7,9)]])
print(array)

# higher-level arrays

array = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(array)

# REMARK: a 3-d array is useful for image data, which contains a grid
# of rgb values

# indexing in an array starts from 0, first row then column

array = np.array([[0,1,2],[3,4,5]])
print('slice:   [0,1]:',array[0,1])
print('access: [0][1]:',array[0][1])

# more on slices later

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
slice:   [0,1]: 1
access: [0][1]: 1


#### Zadatak 3: Ostali načini kreiranja numpy arraya

In [ ]:
array = np.empty(4) 
print("empty\n",array)

array = np.zeros((2,3))
print("zeroes\n",array)

array = np.identity(4)
print("identity\n",array)

array = np.eye(5,4)
print("eye(5,4)\n",array)

array = np.eye(4,5)
print("eye(4,5)\n",array)

array = np.random.random(5)
print("random(5)\n",array)

array = np.random.random([5,5])
print("random([5,5])\n",array)

#### Vježba
Pogledati dokumentaciju: http://numpy.org/doc/1.18/reference/routines.array-creation.html \\

Kako biste kreirali array koji sadrži samo nule, a istih je dimenzija kao neki zadani array?

#### Zadatak 4: Osnovne aritmetičke operacije

In [ ]:
# Elementwise

x = np.array([1,2,3,4])
y = np.array([2,4,6,8])
# Addition
print("x+y= ", x+y)
print("x+y= ",np.add(x,y))

# Substraction
print("x-y= ",x-y)
print("x-y= ",np.subtract(x,y))

#Multiplication
print("x*y= ",x*y)
print("x*y= ",np.multiply(x,y))

# Square root
print("sqrt(x)= ",np.sqrt(x))

# Multiplication of arrays by a scalar 
print("2*x= ",2*x)

In [4]:
# CONCEPT: Broadcasting
# if you were designing numpy, what should the following operation do?

array = np.array([1,2,3]) + 1
print(array)

# what about...

array = np.array([1,2,3]) * np.array([[1],[2],[3]])
print(array)

# and what about!!!

try:
  array = np.array([1,2,3]) + np.array([1,2])
except ValueError as e:
  print('caught ValueError:',e)

# basic idea of broadcasting:
# if two axis are the same length, hadamard-style operations
# if one axis is one element, then extend it to match the other

[2 3 4]
[[1 2 3]
 [2 4 6]
 [3 6 9]]
caught ValueError: operands could not be broadcast together with shapes (3,) (2,) 


#### Zadatak 5: Osnovne aritmetičke operacije - množenje

In [7]:
## Exercise 1: basic operations of numpy: {{{

# the @ operator represents matrix multiplication

# numpy offers the following functions, which are all similar but different:
#
#                vectors     matrices      tensors
# __________________________________________________
# @            | <a,b>    | AA          | ???
# numpy.inner  | <a,b>    | A^T A       | ???
# numpy.dot    | <a,b>    | AA          | ???
# numpy.vdot   | <a*,b>   | A:A         | ???
# numpy.outer  | <a,b^T>  | a11*A a12*A | ???
#                         | a21*A a22*A | ???


##### Inner product 
x = np.array([1,2,3,4])
y = np.array([2,4,6,8])

# Exercise 5.1. Implement inner product using loop
skalarni_produkt = 0
for i in range(x.shape[0]):
    skalarni_produkt += x[i]*y[i]

print(skalarni_produkt)

# Numpy operations: 
print(np.dot(x,y))
print(x.dot(y))
print(np.inner(x,y))

##### Outer product
# Exercise 5.2. Implement outer product using loop
n = x.shape[0]
A = np.empty([4,4])
for i in range(n):
    for j in range(n):
        A[i,j] = x[i]*y[j]
print(A)

# Numpy operations:
print(np.outer(x,y))

##### Matrix * vector multiplication: Ax

# Exercise 5.3 Implement product of matrix A and vector x 
# Ax = b
A = 2*np.eye(4,4)
b = np.zeros([4,1])
for i in range(4):
    for j in range(4):
        b[i] += A[i,j]*x[j]
print(b)

# numpy operations
print(A.dot(x))

##### Multiplication of matrices

A = np.array([[1,2,3],[1,0,1],[1,0, 0]])
B = np.array([[2,2,2],[1,0,-1],[-1, 1, 0]])

C = np.zeros([3,3])
for i in range(3):
    for j in range(3):
        for k in range(3):
            C[i,j] += A[i,k]*B[k,j]
print(C)

# numpy operations
print(np.dot(A,B))
print(np.matmul(A,B))

60
60
60
60
[[ 2.  4.  6.  8.]
 [ 4.  8. 12. 16.]
 [ 6. 12. 18. 24.]
 [ 8. 16. 24. 32.]]
[[ 2  4  6  8]
 [ 4  8 12 16]
 [ 6 12 18 24]
 [ 8 16 24 32]]
[[2.]
 [4.]
 [6.]
 [8.]]
[2. 4. 6. 8.]
[[1. 5. 0.]
 [1. 3. 2.]
 [2. 2. 2.]]
[[1 5 0]
 [1 3 2]
 [2 2 2]]
[[1 5 0]
 [1 3 2]
 [2 2 2]]


#### Zadatak 6: Intervali

In [ ]:
# basic ranges:
# arange([start],stop,[step])
# linspace(start,stop,n=50,endpoint=True)
#
# advanced ranges:
# logspace
# geomspace

# arange
# NOTE: interval is of the form [start,end)

array = np.arange(3,8)
print(array)

array = np.arange(3,11,2)
print(array)

array = np.arange(10,2,-2)
print(array)

#### Zadatak 7: Rješavanje Ax = b, gdje je A gornjetrokutasta

In [8]:
# the technique is back substitution:
# given:  |a b|[x1] = b1
#         |0 c|[x2] = b2
#
# the last equation can be solved trivially.  Then the next to last
# can be solved by using this value, etc.

# A should be upper triangular
def backsub(A,b):
    m,n = A.shape
    r = np.zeros(m)
    m-=1
    for i in range(m,-1,-1):
        r[i] = b[i] - np.dot(r,A[i,n-m-1:])
        if A[i,i] != 0: r[i] /= A[i,i]
        elif r[i] == 0: continue
        else: raise ValueError('backsub not solvable')
    return r

A = np.array([[1,2,3],
              [0,2,1],
              [0,0,4]])
b = np.array([12,10,8])
print(backsub(A,b))

[-2.  4.  2.]


#### Zadatak 8: Stack

In [9]:
# if we have some arrays, we may like to build other arrays or
# matrices from them.  Two useful operations to accomplish this are
# stack and concatenate.
#
# stack takes some arrays and "stacks them up" along a NEW axis. i.e.
#     stack : (R^n1 x R^n2 x ...)^m -> R^m x R^n1 x R^n2 ...
#
# By default, it will stack arrays along a new "outermost" axis, but
# this can be changed with the keyword argument axis

a = np.arange(4)
print(np.stack((a,a,a)))
print(np.stack((a,a,a), axis=1))

a = np.arange(3*4).reshape((3,4))
b = np.arange(3*4).reshape((3,4))

print("a =", a)
print("b= ", b)

print('axis=0',np.stack((a,b)),sep='\n')
print('axis=1',np.stack((a,b),axis=1),sep='\n')
print('axis=2',np.stack((a,b),axis=2),sep='\n')


[[0 1 2 3]
 [0 1 2 3]
 [0 1 2 3]]
[[0 0 0]
 [1 1 1]
 [2 2 2]
 [3 3 3]]
a = [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
b=  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
axis=0
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]]
axis=1
[[[ 0  1  2  3]
  [ 0  1  2  3]]

 [[ 4  5  6  7]
  [ 4  5  6  7]]

 [[ 8  9 10 11]
  [ 8  9 10 11]]]
axis=2
[[[ 0  0]
  [ 1  1]
  [ 2  2]
  [ 3  3]]

 [[ 4  4]
  [ 5  5]
  [ 6  6]
  [ 7  7]]

 [[ 8  8]
  [ 9  9]
  [10 10]
  [11 11]]]


#### Zadatak 9: Concatenate

In [10]:
# concatenate is almost the same as stack, but the difference is that
# no new axis is created, rather an existing axis is extended

a = np.arange(2*3).reshape((2,3))
print("a = ", a)
print(np.concatenate((a,a,a)))
print(np.concatenate((a,a,a),axis=1))

# Translates slice objects to concatenation along the second axis.
# np.c_(X,Y)

a =  [[0 1 2]
 [3 4 5]]
[[0 1 2]
 [3 4 5]
 [0 1 2]
 [3 4 5]
 [0 1 2]
 [3 4 5]]
[[0 1 2 0 1 2 0 1 2]
 [3 4 5 3 4 5 3 4 5]]


#### Zadatak 10: Razno

In [ ]:
# operations like reshape swapaxes, moveaxis, and transpose all
# operate on the shape of the arrays...

a = np.arange(2*3*4*5*6)
b = a.reshape(2,3,4,5,6)
c = np.moveaxis(b,0,2)
d = np.transpose(b)

print('a',a.shape)
print('b',b.shape)
print('c',c.shape)
print('d',d.shape)

# Transpose
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a.T)

#### Zadatak 11: Rad s podacima
1. učitavanje podataka
    - neke od standardnih funkcija koje ćete koristiti iz paketa numpy i pandas
    - podaci su najčešće u formatima: csv, txt, slike
2. spremanje podataka
    - neke od standardnih funkcija za spremanje podataka

In [ ]:
# Primjer: Numpy
# Učitamo neke podatke koji su lokalno spremljeni u .csv
podaci = np.loadtxt('./Podaci/data.csv', delimiter =',')

# Pogledamo koliko podataka ima
podaci.shape

In [ ]:
# Primjer: Pandas - alat za jednostavno manipuliranje podacima
# Učitamo neke podatke koji su lokalno spremljeni u .csv
podaci = pd.read_csv('./podaci/X_a.csv')

# Pregled podataka
print(podaci.head())

# Pogledamo koliko podataka ima
print(podaci.shape)

In [ ]:
# Primjer: 
# numpy.savetxt(fname, X, fmt='%.18e', delimiter=' ', newline='n', header='', footer='', comments='# ', encoding=None)
X = np.random.random([10,2])
np.savetxt('Podaci-1', X)

# DataFrame.to_csv(path_or_buf=None, sep=',', na_rep='', float_format=None, columns=None, header=True, index=True, index_label=None, ...)
X_dataframe = pd.DataFrame(X)
X_dataframe.to_csv('Podaci-2',header=['prvi', 'drugi'])

### Upoznavanje s matplotlib, scikit-learn


#### Zadatak 12:  Vizualizacija podataka
- najčešće korišteno: matplotlib.pyplot
- podaci predstavljaju točke u ravnini: scatter plot
- crtanje grafa ovisnosti jedne varijable o drugoj: plot
- crtanje histograma, matrice korelacije
- crtanje vektora

In [ ]:
# Učitamo neke podatke koji su lokalno spremljeni u .csv
podaci = np.loadtxt('./Podaci/data.csv', delimiter =',')

# Podaci su neke točke oblika (x,y)
plt.scatter(podaci[:,0], podaci[:,1])
plt.show()

# Crtanje grafa funkcije 
x = np.arange(0,10,0.5)
y = x**2 + 2*x + 5
plt.plot(x,y, color='mediumaquamarine')
plt.scatter([4],[29], color='midnightblue')
plt.show()

# Drugi način
plt.scatter(x,y)
plt.show()

# Crtanje pravca
x = np.array([2,5])
y = np.array([2,5])
plt.plot(x,y)
plt.show()



In [ ]:
# Unutar paketa scikit-learn postoje neki standardni datasetovi koje možete koristiti
# Svi se učitavaju na sljedeći način: 
dataset = datasets.load_breast_cancer()
df = pd.DataFrame(data= dataset['data'],columns= dataset['feature_names'])
df